### ISSUE TITLE
Making the Project Kid-Friendly?

### ISSUE THREAD

**Issue by FlipperPA** [sepandhaghighi/art#264]
#### Description

I've used this package as a great starting point to get kids interested in coding, and showing them how to read documentation to figure out how packages and their functions work. However, when importing lists of available art items such as `ASCII_ARTS`, there are some very non-kid-friendly items (`fat ass`, `fuck off`, `fuck you`, `old lady boobs`, `penis`). I realize this is ASCII art, and I'm hardly the clutch-the-pearls type, but could we maybe make this main repo G-rated and create an `art-adult` secondary package for the rest of the stuff? I had an 11-year-old stumble across these items, and it wasn't the greatest moment to have to explain to their parents what happened.

#### Steps/Code to Reproduce

```python
from art import ASCII_ARTS

print(ASCII_ARTS)
```

#### ART Version (Use : `art.__version__`)
6.1

**Comment by sepandhaghighi** [comment]
@FlipperPA ✋ 

I apologize for the delay in my response. We have reviewed your suggestion and we understand and respect your concern ❤️ However, we believe that creating a `kid-friendly` mode for the original repo is outside the scope of our project.

We have two suggestions for you:

1. You can download the `art` source code and remove those parts. Then, you can install it locally instead of using `pypi` or `anaconda`.

2. Alternatively, you can fork the library, make the necessary modifications, and release it under a new name, such as `art-kid`.

Please don't hesitate to ask if you have any further questions.

Best,
SH

**Comment by FlipperPA** [comment]
@sepandhaghighi Thanks so much for the reply, I very much appreciate it. I'll fork!
