### ISSUE TITLE
[Feature]: Line function

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/art#272]
### Describe the feature you want to add

Adding line functions to `art`

```python
from art import line, lprint
lprint(length=10, height=1, char="#")
##########
lprint(length=15, height=2, char="*")
***************
***************
line(length=10, height=1, char="#")
"##########"
line(length=15, height=2, char="*")
"***************\n***************"
```

### Additional context

**Default values:**

1. length: 15
2. height: 1
3. char: `#`

**Comment by sepandhaghighi** [comment]
@AHReccese

Are you interested in taking care of this issue?

**Comment by AHReccese** [comment]
Yes, sure. I would be honored. 
@sepandhaghighi

**Comment by sepandhaghighi** [comment]
@AHReccese
Feel free to begin this task.

**Comment by AHReccese** [comment]
@sepandhaghighi 
Hi Sepand, I'm developing this feature, just in order to make sure I'm on the same page with you on the requested feature, I have some questions:

1. The functino signature for `lprint` is `int, int, char` and I should print a grid of this char with associated length and height, is there any other options? selecting font for example like `tprint`?
2. and the `lprint` function, basically `prints` the `line` function output right? I mean `line` returns `str` but `lprint` doesn't return anything, instead it prints to console.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Hi Sepand, I'm developing this feature, just in order to make sure I'm on the same page with you on the requested feature, I have some questions:
> 
> 1. The functino signature for `lprint` is `int, int, char` and I should print a grid of this char with associated length and height, is there any other options? selecting font for example like `tprint`?
> 2. and the `lprint` function, basically `prints` the `line` function output right? I mean `line` returns `str` but `lprint` doesn't return anything, instead it prints to console.

@AHReccese Hi

1. No. `lprint` and `line` should only accept `char`, `height`, and `length` parameters

2. Yes exactly!
